# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python= 3.13.5                 # https://pyreadiness.org/3.10
  - uv=0.8.17                    # https://pip.pypa.io/en/stable/news
  - pip:
    - robocorp==3.0.0             # https://pypi.org/project/robocorp
    - robocorp-truststore==0.9.1  # https://pypi.org/project/robocorp-truststore/
    - psycopg2-binary>=2.9.9          # https://pypi.org/project/psycopg2-binary/ (PostgreSQL adapter)
    - redis>=5.0.0                    # https://pypi.org/project/redis/ (Redis adapter)
    - sqlalchemy>=2.0.0               # https://pypi.org/project/SQLAlchemy/ (Database toolkit for PostgreSQL pooling)
